language: java
script: mvn -Psafer -Passembler -Pcoverage -B -e -T 1C verify
jdk:
- oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false
  
before_script:
  - export GIT_BRANCH=$TRAVIS_BRANCH  
  
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"