language: java
script: mvn -Psafer -Pintegration -Passembler -Pcoverage -B -e -T 1C verify
jdk:
- oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
  postgresql: "9.6"

services:
  - postgresql

sudo: false

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database test;' -U test

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
