site_name: ToroDB Stampede
theme: readthedocs
pages:
- About: index.md
- 'Quickstart': quickstart.md
- 'Installation and configuration': installation.md
- 'How to use?': how-to-use.md
- 'Appendix': appendix.md
